sudo: false

os: linux

dist: trusty

python:
  - 2.7
  - 3.6

language: python

cache:
  - pip

notifications:
  email: false

branches:
  only:
    - master

install:
  - pip install opencv-python
  - pip install Cython
  - pip install .

script:
  - pip install flake8 pytest
  - flake8 .
  - pytest -v tests -m 'not gpu'
  # examples
  - (cd examples/coco && ./convert_caffe2_to_chainer.py && ./demo.py logs/R-50-C4_x1_caffe2_to_chainer --gpu -1)
