sudo: false

os: linux

dist: trusty

python:
  - 2.7
  - 3.6

language: python

cache:
  - pip

install:
  - pip install flake8 pytest
  - pip install opencv-python
  - pip install Cython
  - pip install .

script:
  - flake8 .
  - pytest -v tests -m 'not gpu'

notifications:
  email: false

branches:
  only:
    - master
