sudo: false

os: linux

dist: trusty

python:
  - 2.7
  - 3.6

language: python

cache:
  - pip

notifications:
  email: false

branches:
  only:
    - master

install:
  - pip install opencv-python
  - pip install Cython
  - pip install .

script:
  - pip install hacking pytest
  - flake8 .
  - pytest -v tests -m 'not gpu'

  # run example.
  - (cd examples/coco && ./convert_caffe2_to_chainer.py)
