name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7]

    steps:
    - uses: actions/checkout@v1

    - name: Update submodules
      run: |
        git submodule update --init --recursive

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ "${{ matrix.python-version }}" = "2.7" ]; then
          pip install numpy==1.16.5
          pip install matplotlib==2.2.4
        fi
        pip install cython
        pip install opencv-python
        pip install -r requirements.txt

    - name: Install main
      run: |
        pip install .

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Test with pytest
      env:
        MPLBACKEND: agg
      run: |
        pip install pytest
        pytest tests -m 'not gpu'

    - name: Run example
      env:
        MPLBACKEND: agg
      run: |
        (cd examples/coco && ./convert_caffe2_to_chainer.py)

    - name: Install from dist
      run: |
        rm -f dist/*.tar.gz
        python setup.py sdist
        pip install dist/*.tar.gz
